# Generated by Django 5.2.8 on 2025-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('refreshToken', models.CharField(max_length=2000)),
                ('tokenUri', models.CharField(max_length=200)),
                ('clientId', models.CharField(max_length=200)),
                ('clientSecret', models.CharField(max_length=200)),
                ('scopes', models.CharField(max_length=200)),
                ('universeDomain', models.CharField(max_length=200)),
                ('account', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry', models.CharField(max_length=200)),
            ],
        ),
    ]
