# Generated by Django 5.2.8 on 2025-11-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=2000),
        ),
    ]
