# Generated by Django 5.2.8 on 2025-11-06 17:42

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionTitle', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.TextField()),
                ('bio', models.TextField()),
                ('profileImage', models.URLField(max_length=2500)),
                ('details', models.JSONField(default=dict)),
                ('cvLink', models.URLField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.URLField(max_length=2500)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="What I <span class='text-yellow-500'>Provide</span>\n Add span tag with tailwing to highlight", max_length=200)),
                ('subtitle', models.CharField(help_text='Must be uppercase', max_length=200)),
                ('services', models.ManyToManyField(blank=True, to='portfolioApi.services')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='Meta description for the blog post')),
                ('coverImage', models.URLField(max_length=2500)),
                ('content', django_quill.fields.QuillField()),
                ('readMin', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolioApi.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(help_text='Meta description for the blog post')),
                ('coverImage', models.URLField(max_length=2500)),
                ('content', models.CharField(max_length=2500)),
                ('tag', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolioApi.skills')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionTitle', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('skills', models.ManyToManyField(blank=True, to='portfolioApi.skills')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('highlight', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.pages')),
                ('socialLinks', models.ManyToManyField(blank=True, to='portfolioApi.sociallinks')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.JSONField(default=dict, help_text='[\n \\{\n      "label": "Address",\n      "value": "New Delhi, Delhi, India",\n      "icon": "map-pin"\n    \\}')),
                ('socialLinks', models.ManyToManyField(blank=True, to='portfolioApi.sociallinks')),
            ],
        ),
    ]
