# Generated by Django 5.2.8 on 2025-11-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='page',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='socialLinks',
        ),
        migrations.AddField(
            model_name='blogs',
            name='temp_image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='details',
            field=models.JSONField(default=dict, help_text='{"Phone": "Ph no","Email": "email","Address": "Address","Language": "English, Hindi (Multilingual abilities)"}'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
