# Generated by Django 5.2.8 on 2025-11-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0003_alter_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='coverImage',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
