# Generated by Django 5.2.8 on 2025-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0005_alter_blogs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
